# Form implementation generated from reading ui file 'autorisation_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Autorisation_Dialog(object):
    def setupUi(self, Autorisation_Dialog):
        Autorisation_Dialog.setObjectName("Autorisation_Dialog")
        Autorisation_Dialog.resize(395, 255)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Autorisation_Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 360, 188))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.login_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.login_label.setFont(font)
        self.login_label.setObjectName("login_label")
        self.verticalLayout.addWidget(self.login_label)
        self.login_lineEdit = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.login_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.login_lineEdit.setObjectName("login_lineEdit")
        self.verticalLayout.addWidget(self.login_lineEdit)
        self.password_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.password_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.verticalLayout.addWidget(self.password_label)
        self.password_lineEdit = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.password_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.verticalLayout.addWidget(self.password_lineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.registration_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.registration_button.setMinimumSize(QtCore.QSize(0, 30))
        self.registration_button.setObjectName("registration_button")
        self.horizontalLayout.addWidget(self.registration_button)
        self.dialog_buttonBox = QtWidgets.QDialogButtonBox(parent=self.verticalLayoutWidget)
        self.dialog_buttonBox.setMinimumSize(QtCore.QSize(0, 50))
        self.dialog_buttonBox.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.dialog_buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dialog_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dialog_buttonBox.setObjectName("dialog_buttonBox")
        self.horizontalLayout.addWidget(self.dialog_buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(parent=Autorisation_Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Autorisation_Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 361, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Autorisation_Dialog)
        self.dialog_buttonBox.accepted.connect(Autorisation_Dialog.accept) # type: ignore
        self.dialog_buttonBox.rejected.connect(Autorisation_Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Autorisation_Dialog)
        Autorisation_Dialog.setTabOrder(self.login_lineEdit, self.password_lineEdit)

    def retranslateUi(self, Autorisation_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Autorisation_Dialog.setWindowTitle(_translate("Autorisation_Dialog", "Baby Type Lite: авторизация"))
        self.login_label.setText(_translate("Autorisation_Dialog", "Логин:"))
        self.password_label.setText(_translate("Autorisation_Dialog", "Пароль:"))
        self.registration_button.setText(_translate("Autorisation_Dialog", "Зарегистрироваться"))
        self.label.setText(_translate("Autorisation_Dialog", "Чтобы продолжить, войдите в свой аккаунт"))
        self.label_2.setText(_translate("Autorisation_Dialog", "или создайте новый"))
