# Form implementation generated from reading ui file 'level.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Level(object):
    def setupUi(self, Level):
        Level.setObjectName("Level")
        Level.resize(1000, 700)
        Level.setMinimumSize(QtCore.QSize(1000, 700))
        Level.setMaximumSize(QtCore.QSize(1000, 700))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Light, brush)
        Level.setPalette(palette)
        self.output = QtWidgets.QTextEdit(parent=Level)
        self.output.setGeometry(QtCore.QRect(150, 160, 701, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output.sizePolicy().hasHeightForWidth())
        self.output.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.output.setFont(font)
        self.output.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.output.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
        self.output.setOverwriteMode(False)
        self.output.setObjectName("output")
        self.input = QtWidgets.QTextEdit(parent=Level)
        self.input.setGeometry(QtCore.QRect(240, 640, 531, 151))
        self.input.setObjectName("input")
        self.back_to_main_button = QtWidgets.QPushButton(parent=Level)
        self.back_to_main_button.setGeometry(QtCore.QRect(150, 50, 121, 65))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back_to_main_button.setFont(font)
        self.back_to_main_button.setObjectName("back_to_main_button")
        self.time_label = QtWidgets.QLabel(parent=Level)
        self.time_label.setGeometry(QtCore.QRect(280, 10, 431, 141))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.time_label.setFont(font)
        self.time_label.setText("")
        self.time_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.start_button = QtWidgets.QPushButton(parent=Level)
        self.start_button.setGeometry(QtCore.QRect(430, 320, 151, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.leader_button = QtWidgets.QPushButton(parent=Level)
        self.leader_button.setGeometry(QtCore.QRect(730, 50, 121, 65))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.leader_button.setFont(font)
        self.leader_button.setObjectName("leader_button")
        self.page_number_label = QtWidgets.QLabel(parent=Level)
        self.page_number_label.setGeometry(QtCore.QRect(430, 560, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.page_number_label.setFont(font)
        self.page_number_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.page_number_label.setText("")
        self.page_number_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.page_number_label.setObjectName("page_number_label")

        self.retranslateUi(Level)
        QtCore.QMetaObject.connectSlotsByName(Level)

    def retranslateUi(self, Level):
        _translate = QtCore.QCoreApplication.translate
        Level.setWindowTitle(_translate("Level", "Form"))
        self.output.setHtml(_translate("Level", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.back_to_main_button.setText(_translate("Level", "Назад в меню\n"
"выбора уровня"))
        self.start_button.setText(_translate("Level", "Начать"))
        self.leader_button.setText(_translate("Level", "Таблица \n"
"лидеров"))
