# Form implementation generated from reading ui file 'wrong_login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Wrong_Login(object):
    def setupUi(self, Wrong_Login):
        Wrong_Login.setObjectName("Wrong_Login")
        Wrong_Login.resize(401, 149)
        self.wrong_login_buttonBox = QtWidgets.QDialogButtonBox(parent=Wrong_Login)
        self.wrong_login_buttonBox.setGeometry(QtCore.QRect(0, 100, 401, 32))
        self.wrong_login_buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.wrong_login_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.wrong_login_buttonBox.setCenterButtons(True)
        self.wrong_login_buttonBox.setObjectName("wrong_login_buttonBox")
        self.label = QtWidgets.QLabel(parent=Wrong_Login)
        self.label.setGeometry(QtCore.QRect(0, 30, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Wrong_Login)
        self.wrong_login_buttonBox.accepted.connect(Wrong_Login.accept) # type: ignore
        self.wrong_login_buttonBox.rejected.connect(Wrong_Login.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Wrong_Login)

    def retranslateUi(self, Wrong_Login):
        _translate = QtCore.QCoreApplication.translate
        Wrong_Login.setWindowTitle(_translate("Wrong_Login", "Dialog"))
        self.label.setText(_translate("Wrong_Login", "Неправильный логин или пароль!"))
